### ISSUE TITLE
Make sure we can pass more than one values to entity reference fields

### ISSUE THREAD

**Issue by ademarco** [nuvoleweb/drupal-behat#10]
### Scope
Given the following:

```gherkin
    Given "tags" terms:
      | name  |
      | Tag 1 |
      | Tag 2 |

    And the following content:
      """
      title: Article title
      type: article
      langcode: en
      field_tags: Tag 1
      body: Article body

      field_paragraphs:
        -
          type: jumbotron
          field_title: Jumbotron title
          field_subtitle: Jumbotron subtitle
      """
````

Both this notations will throw errors:

```
      field_tags: Tag 1, Tag 2
      ...
      field_tags: 
        - Tag 1
        - Tag 2
```

We should support both of them.

### Tasks
- [ ] Support multiple values on entity reference field
- [ ] Treat both `entity_reference` and `entity_reference_revisions` the same by allowing the entity to be loaded by name if the value is just a string (like now nodes and terms) or by creating it recursively if it is an array (like now paragraphs)
- [ ] Consider integrate that in upstream Drupal Behat extension

**Comment by bircher** [comment]
The following should work:
```
    Given "tags" terms:
      | name  |
      | Tag 1 |
      | Tag 2 |

    And the following content:
      """
      title: Article one tag
      type: article
      langcode: en
      field_tags: Tag 1
      body: Article body
      """

    And the following content:
      """
      title: Article two tags
      type: article
      langcode: en
      body: Article body
      field_tags:
        - Tag 1
        - Tag 2
      """

    And the following content:
      """
      title: Article new tag
      type: article
      langcode: en
      body: Article body
      field_tags:
        -
          type: tags
          name: Tag 3
      """


    And the following content:
      """
      title: Article mixed new and existing
      type: article
      langcode: en
      body: Article body
      field_tags:
        - Tag 2
        -
          type: tags
          name: Tag 4
      """
```

Of course this should work with all entity types that have a label key to be loaded by name (not just taxonomy terms and nodes) and any entity should be able to be created, also with nested entity references.

**Comment by bircher** [comment]
bonus if this also works
```
    And the following content:
      """
      title: Article new tag
      type: article
      langcode: en
      body: Article body
      field_tags:
        type: tags
        name: Just one new tag
      """
```
